name: Build and Publish Back and DB Images

on:
  push:
    branches: ["main", "QA", "dev"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  # Definimos nombres base para las dos imágenes
  BACK_IMAGE_NAME: ${{ github.repository }}
  DB_IMAGE_NAME: ${{ github.repository_owner }}/perfumes-db

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- CONFIGURACIÓN PARA EL BACKEND ---
      - name: Metadatos Backend
        id: meta_back
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACK_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Construir y subir Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ steps.meta_back.outputs.tags }}
          labels: ${{ steps.meta_back.outputs.labels }}

      # --- CONFIGURACIÓN PARA LA BASE DE DATOS ---
      - name: Metadatos DB
        id: meta_db
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.DB_IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Construir y subir DB
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./db.dockerfile
          push: true
          tags: ${{ steps.meta_db.outputs.tags }}
          labels: ${{ steps.meta_db.outputs.labels }}